from dataclasses import dataclass
from typing import List


@dataclass(frozen=True)
class Task:
    task_name: str
    input_templates: List[str]
    output_templates: List[str]


# Templates
# It is important that the tasks are in order of priority (lowest to highest)
# Priority is important because we check which task is it by using the `phrases`
# It is important to be lowest to highest because we do a reversed when we do the checking (so this is an implementation detail)

# The no_templates templates, to allow for a new baseline: one where we do not
# explicitly instruct the model what to predict
# This construction helps because it will allow everything to work by just
# setting `--template_name no_templates`
no_templates = {
    "task1": {
        "inputs": ["input1"],
        "input1": "$TEXT",
        "phrases": [],
        "output": "$AT",
        "outputs": ["output"],
    },
    "task2": {
        "input1": "$TEXT",
        "inputs": [
            "input1",
        ],
        "phrases": [],
        "output": "$AT is $S",
        "outputs": ["output"],
    },
    "task3": {
        "input1": "$TEXT",
        "inputs": ["input1"],
        "phrases": [],
        "output1": "$AT is $S means $AC $S",
        "outputs": ["output1"],
    },
    "task4": {
        "input1": "$TEXT",
        "inputs": ["input1"],
        "phrases": [],
        "output1": "$AT is $OT means $DOMAIN is $S",
        "outputs": ["output1"],
    },
    "task5": {
        # the templates are such that aspect term, opinion term always comes before sentiment and category
        "input1": "$TEXT",
        "inputs": ["input1"],
        "phrases": [],
        "output1": "$AT is $OT means $AC $S",
        "outputs": ["output1"],
    },
}

# The noisy templates
# They are named noisy because they are used in conjuction with the weakly annotated data
# Some templates contain the word `noisy` (i.e. `what are the noisy aspect terms`)
noisy_templates = {
    "ate": {
        "inputs": [
            "input1",
            "input2",
            "input3",
            "input4",
            "input5",
            "input6",
        ],  # the inputs; one of them will be selected to serve as template, and $TEXT will be replaced
        "input1": """Given the text:\n$TEXT\nWhat are the aspect terms in it ?\n""",
        "input2": """What are the noisy aspect terms in the following text:\n$TEXT\n""",
        "input3": """Please read the following text:\n$TEXT\nWhat are some the aspect terms in it ?""",
        "input4": """Read the following text and extract some of the aspect terms in it:\n$TEXT\n""",
        "input5": """Given the following text:\n$TEXT\nPlease extract some of the aspect terms present in it""",
        "input6": """The task is to extract the noisy aspect terms from the following text:\n$TEXT\n""",
        "phrases": [
            "What are the aspect terms in it",
            "What are the noisy aspect terms in the following text",
            "What are some the aspect terms in it",
            "Read the following text and extract some of the aspect terms in it",
            "Please extract some of the aspect terms present in it",
            "The task is to extract the noisy aspect terms from the following text",
        ],
        "output": "$AT",
        "outputs": ["output"],
    },
    "ote": {
        "inputs": ["input1", "input2", "input3", "input4", "input5", "input6"],
        "input1": """Given the text:\n$TEXT\nWhat are some of the opinion terms in it ?\n""",
        "input2": """What are the noisy opinion terms in the following text:\n$TEXT\n""",
        "input3": """Please read the following text:\n$TEXT\nWhat are the opinion terms in it ?""",
        "input4": """Read the following text and extract the opinion terms:\n$TEXT\n""",
        "input5": """The task is to extract some of the opinion terms present in the following text:\n$TEXT\n""",
        "input6": """Given the next text:\n$TEXT\nWhat are the opinion terms in it ?""",
        "phrases": [
            "What are some of the opinion terms in it",
            "What are the noisy opinion terms in the following text",
            "What are the opinion terms in it",
            "Read the following text and extract the opinion terms",
            "The task is to extract some of the opinion terms present in the following text",
            "What are the opinion terms in it",
        ],
        "output": "$OT",
        "outputs": ["output"],
    },
    "ate_ote": {
        "inputs": ["input1", "input2", "input3", "input4"],
        "input1": """Given the text:\n$TEXT\nWhat are some of the aspect term, opinion term pairs ?\n""",
        "input2": """What are the aspect terms and opinion terms pairs expressed in the following text:\n$TEXT\n""",
        "input3": """What are the aspect term, opinion term pairs in the text: $TEXT ?""",
        "input4": """Extract the aspect terms and their opinion terms from the following text:\n$TEXT\n""",
        "phrases": [
            "What are some of the aspect term, opinion term pairs",
            "What are the aspect terms and opinion terms pairs expressed in the following text",
            "What are the aspect term, opinion term pairs in the text",
            "Extract the aspect terms and their opinion terms from the following text",
        ],
        "output": "$AT is described as $OT",
        "outputs": ["output"],
    },
    "ate_sent": {
        "inputs": ["input1", "input2", "input3"],
        "input1": """Given the text:\n$TEXT\nWhat are some of the aspect terms and their sentiment ?\n""",
        "input2": """What are the aspect terms and their associated sentiment in the following text:\n$TEXT\n""",
        "input3": """Extract the aspect terms and their sentiment from the following text:\n$TEXT\n""",
        "phrases": [
            "What are some of the aspect terms and their sentiment",
            "What are the aspect terms and their associated sentiment in the following text",
            "Extract the aspect terms and their sentiment from the following text",
        ],
        "output": "$AT is $S",
        "outputs": ["output"],
    },
    "ate_ote_sent": {
        "inputs": ["input1", "input2", "input3"],
        "input1": """Given the text:\n$TEXT\nWhat are some of the aspect term, opinion term and sentiment triplets ?\n""",
        "input2": """What are the aspect terms, opinion terms and their associated sentiment in the following text:\n$TEXT\n""",
        "input3": """Extract the aspect term, opinion term and sentiment triplets in the following text:\n$TEXT\n""",
        "phrases": [
            "What are some of the aspect term, opinion term and sentiment triplets",
            "What are the aspect terms, opinion terms and their associated sentiment in the following text",
            "Extract the aspect term, opinion term and sentiment triplets in the following text",
        ],
        "output": "$AT is $S because it is described as $OT",
        "outputs": ["output"],
    },
}

main_templates = {
    "task1": {
        # "input1": "What are the terms in the text \"$TEXT\" that have opinion expressed towards them?",
        # "input2": "In the following text : \"$TEXT\", what are the terms that have opinion expressed towards them?",
        # "input3": "In the following text : \"$TEXT\", what are the real world entities that are worthy of a subjective opinion?","
        "inputs": ["input1", "input2"],
        "input1": "Given the text: $TEXT, what are the aspect terms in it ?",
        "input2": "What are the aspect terms in the text: $TEXT ?",
        "phrases": ["aspect terms"],
        "output": "$AT",
        "outputs": ["output"],
    },
    "task2": {
        "input1": "Given the text: $TEXT, what are the aspect terms and their sentiments ?",
        "input2": "What are the aspect terms and their sentiments in the text: $TEXT ?",
        "input3": "Given the text: $TEXT, what are the aspect term, sentiment pairs ?",
        "input4": "What are the aspect term, sentiment pairs in the text: $TEXT ?",
        "inputs": ["input1", "input2", "input3", "input4"],
        "phrases": [
            "aspect terms and their sentiments",
            "aspect term, sentiment pairs",
        ],
        "output": "$AT is $S",
        "outputs": ["output"],
    },
    "task3": {
        "input1": "Given the text: $TEXT, what are the aspect term, sentiment and category triplets ?",
        "input2": "What are the aspect term, sentiment and category triplets in the text: $TEXT ?",
        "input3": "Given the text: $TEXT, what are the aspect term, category and sentiment triplets ?",
        "input4": "What are the aspect term, category and sentiment triplets in the text: $TEXT ?",
        "inputs": ["input1", "input2", "input3", "input4"],
        "phrases": [
            "aspect term, sentiment and category triplets",
            "aspect term, category and sentiment triplets",
        ],
        "output1": "$AT is $S means $AC $S",
        "output2": "$AC $S because $AT is $S",
        "outputs": ["output1"],
    },
    "task4": {
        "input1": "Given the text: $TEXT, what are the aspect term, opinion term and sentiment triplets ?",
        "input2": "What are the aspect term, opinion term and sentiment triplets in the text: $TEXT ?",
        "input3": "Given the text: $TEXT, what are the opinion term, aspect term and sentiment triplets ?",
        "input4": "What are the opinion term, aspect term and sentiment triplets in the text: $TEXT ?",
        "inputs": ["input1", "input2", "input3", "input4"],
        "phrases": [
            "aspect term, opinion term and sentiment triplets",
            "opinion term, aspect term and sentiment triplets",
        ],
        "output1": "$AT is $OT means $DOMAIN is $S",
        "output2": "$DOMAIN is $S because $AT is $OT",
        "outputs": ["output1"],
    },
    "task5": {
        # the templates are such that aspect term, opinion term always comes before sentiment and category
        "input1": "Given the text: $TEXT, what are the aspect term, opinion term, sentiment and category quadruples ?",
        "input2": "What are the aspect term, opinion term, sentiment and category quadruples in the text: $TEXT ?",
        "input3": "Given the text: $TEXT, what are the aspect term, opinion term, category and sentiment quadruples ?",
        "input4": "What are the aspect term, opinion term, category and sentiment quadruples in the text: $TEXT ?",
        "input5": "Given the text: $TEXT, what are the opinion term, aspect term, sentiment and category quadruples ?",
        "input6": "What are the opinion term, aspect term, sentiment and category quadruples in the text: $TEXT ?",
        "input7": "Given the text: $TEXT, what are the opinion term, aspect term, category and sentiment quadruples ?",
        "input8": "What are the opinion term, aspect term, category and sentiment quadruples in the text: $TEXT ?",
        "inputs": [
            "input1",
            "input2",
            "input3",
            "input4",
            "input5",
            "input6",
            "input7",
            "input8",
        ],
        "phrases": [
            "aspect term, opinion term, sentiment and category quadruples",
            "aspect term, opinion term, category and sentiment quadruples",
            "opinion term, aspect term, sentiment and category quadruples",
            "opinion term, aspect term, category and sentiment quadruples",
        ],
        "output1": "$AT is $OT means $AC $S",
        "output2": "$AC $S because $AT is $OT",
        "outputs": ["output1"],
    },
}

sentword2opinion = {"positive": "great", "negative": "bad", "neutral": "ok"}


categories2text = {
    "AMBIENCE#GENERAL": "ambience in general is",
    "ambience general": "ambience in general is",
    "BATTERY#DESIGN_FEATURES": "battery design features are",
    "battery design_features": "battery design features are",
    "BATTERY#GENERAL": "battery in general is",
    "battery general": "battery in general is",
    "BATTERY#OPERATION_PERFORMANCE": "battery operation performance is",
    "battery operation_performance": "battery operation performance is",
    "BATTERY#QUALITY": "battery quality is",
    "battery quality": "battery quality is",
    "COMPANY#DESIGN_FEATURES": "company design features are",
    "company design_features": "company design features are",
    "COMPANY#GENERAL": "company in general is",
    "company general": "company in general is",
    "COMPANY#OPERATION_PERFORMANCE": "company operation performance is",
    "company operation_performance": "company operation performance is",
    "COMPANY#PRICE": "company price is",
    "company price": "company price is",
    "COMPANY#QUALITY": "company quality is",
    "company quality": "company quality is",
    "CPU#DESIGN_FEATURES": "cpu design features are",
    "cpu design_features": "cpu design features are",
    "CPU#GENERAL": "cpu in general is",
    "cpu general": "cpu in general is",
    "CPU#OPERATION_PERFORMANCE": "cpu operation performance is",
    "cpu operation_performance": "cpu operation performance is",
    "CPU#PRICE": "cpu price is",
    "cpu price": "cpu price is",
    "CPU#QUALITY": "cpu quality is",
    "cpu quality": "cpu quality is",
    "DISPLAY#DESIGN_FEATURES": "display design features are",
    "display design_features": "display design features are",
    "DISPLAY#GENERAL": "display in general is",
    "display general": "display in general is",
    "DISPLAY#OPERATION_PERFORMANCE": "display operation performance is",
    "display operation_performance": "display operation performance is",
    "DISPLAY#PRICE": "display price is",
    "display price": "display price is",
    "DISPLAY#QUALITY": "display quality is",
    "display quality": "display quality is",
    "DISPLAY#USABILITY": "display usability is",
    "display usability": "display usability is",
    "DRINKS#PRICES": "drinks prices are",
    "drinks prices": "drinks prices are",
    "DRINKS#QUALITY": "drinks quality is",
    "drinks quality": "drinks quality is",
    "DRINKS#STYLE_OPTIONS": "drinks style options are",
    "drinks style_options": "drinks style options are",
    "FANS&COOLING#DESIGN_FEATURES": "fans and cooling design features are",
    "fans&cooling design_features": "fans and cooling design features are",
    "FANS&COOLING#GENERAL": "fans and cooling in general is",
    "fans&cooling general": "fans and cooling in general is",
    "FANS&COOLING#OPERATION_PERFORMANCE": "fans and cooling operation performance is",
    "fans&cooling operation_performance": "fans and cooling operation performance is",
    "FANS&COOLING#QUALITY": "fans and cooling quality is",
    "fans&cooling quality": "fans and cooling quality is",
    "FOOD#GENERAL": "food in general is",
    "food general": "food in general is",
    "FOOD#PRICES": "food prices are",
    "food prices": "food prices are",
    "FOOD#QUALITY": "food quality is",
    "food quality": "food quality is",
    "FOOD#STYLE_OPTIONS": "food style options are",
    "food style_options": "food style options are",
    "GRAPHICS#DESIGN_FEATURES": "graphics design features are",
    "graphics design_features": "graphics design features are",
    "GRAPHICS#GENERAL": "graphics in general is",
    "graphics general": "graphics in general is",
    "GRAPHICS#OPERATION_PERFORMANCE": "graphics operation performance is",
    "graphics operation_performance": "graphics operation performance is",
    "GRAPHICS#USABILITY": "graphics usability is",
    "graphics usability": "graphics usability is",
    "HARDWARE#DESIGN_FEATURES": "hardware design features are",
    "hardware design_features": "hardware design features are",
    "HARDWARE#GENERAL": "hardware in general is",
    "hardware general": "hardware in general is",
    "HARDWARE#OPERATION_PERFORMANCE": "hardware operation performance is",
    "hardware operation_performance": "hardware operation performance is",
    "HARDWARE#PRICE": "hardware price is",
    "hardware price": "hardware price is",
    "HARDWARE#QUALITY": "hardware quality is",
    "hardware quality": "hardware quality is",
    "HARDWARE#USABILITY": "hardware usability is",
    "hardware usability": "hardware usability is",
    "HARD_DISC#DESIGN_FEATURES": "hard_disc design features are",
    "hard_disc design_features": "hard_disc design features are",
    "HARD_DISC#GENERAL": "hard disc in general is",
    "hard_disc general": "hard disc in general is",
    "HARD_DISC#MISCELLANEOUS": "hard disc miscellaneous is",
    "hard_disc miscellaneous": "hard disc miscellaneous is",
    "HARD_DISC#OPERATION_PERFORMANCE": "hard disc operation performance is",
    "hard_disc operation_performance": "hard disc operation performance is",
    "HARD_DISC#PRICE": "hard disc price is",
    "hard_disc price": "hard disc price is",
    "HARD_DISC#QUALITY": "hard disc quality is",
    "hard_disc quality": "hard disc quality is",
    "HARD_DISC#USABILITY": "hard disc usability is",
    "hard_disc usability": "hard disc usability is",
    "KEYBOARD#DESIGN_FEATURES": "keyboard design features are",
    "keyboard design_features": "keyboard design features are",
    "KEYBOARD#GENERAL": "keyboard in general is",
    "keyboard general": "keyboard in general is",
    "KEYBOARD#MISCELLANEOUS": "keyboard miscellaneous is",
    "keyboard miscellaneous": "keyboard miscellaneous is",
    "KEYBOARD#OPERATION_PERFORMANCE": "keyboard operation performance is",
    "keyboard operation_performance": "keyboard operation performance is",
    "KEYBOARD#PORTABILITY": "keyboard portability is",
    "keyboard portability": "keyboard portability is",
    "KEYBOARD#PRICE": "keyboard price is",
    "keyboard price": "keyboard price is",
    "KEYBOARD#QUALITY": "keyboard quality is",
    "keyboard quality": "keyboard quality is",
    "KEYBOARD#USABILITY": "keyboard usability is",
    "keyboard usability": "keyboard usability is",
    "LAPTOP#CONNECTIVITY": "laptop connectivity is",
    "laptop connectivity": "laptop connectivity is",
    "LAPTOP#DESIGN_FEATURES": "laptop design features are",
    "laptop design_features": "laptop design features are",
    "LAPTOP#GENERAL": "laptop in general is",
    "laptop general": "laptop in general is",
    "LAPTOP#MISCELLANEOUS": "laptop miscellaneous is",
    "laptop miscellaneous": "laptop miscellaneous is",
    "LAPTOP#OPERATION_PERFORMANCE": "laptop operation performance is",
    "laptop operation_performance": "laptop operation performance is",
    "LAPTOP#PORTABILITY": "laptop portability is",
    "laptop portability": "laptop portability is",
    "LAPTOP#PRICE": "laptop price is",
    "laptop price": "laptop price is",
    "LAPTOP#QUALITY": "laptop quality is",
    "laptop quality": "laptop quality is",
    "LAPTOP#USABILITY": "laptop usability is",
    "laptop usability": "laptop usability is",
    "LOCATION#GENERAL": "location in general is",
    "location general": "location in general is",
    "MEMORY#DESIGN_FEATURES": "memory design features are",
    "memory design_features": "memory design features are",
    "MEMORY#GENERAL": "memory in general is",
    "memory general": "memory in general is",
    "MEMORY#OPERATION_PERFORMANCE": "memory operation performance is",
    "memory operation_performance": "memory operation performance is",
    "MEMORY#QUALITY": "memory quality is",
    "memory quality": "memory quality is",
    "MEMORY#USABILITY": "memory usability is",
    "memory usability": "memory usability is",
    "MOTHERBOARD#GENERAL": "motherboard in general is",
    "motherboard general": "motherboard in general is",
    "MOTHERBOARD#OPERATION_PERFORMANCE": "motherboard operation performance is",
    "motherboard operation_performance": "motherboard operation performance is",
    "MOTHERBOARD#QUALITY": "motherboard quality is",
    "motherboard quality": "motherboard quality is",
    "MOUSE#DESIGN_FEATURES": "mouse design features are",
    "mouse design_features": "mouse design features are",
    "MOUSE#GENERAL": "mouse in general is",
    "mouse general": "mouse in general is",
    "MOUSE#USABILITY": "mouse usability is",
    "mouse usability": "mouse usability is",
    "MULTIMEDIA_DEVICES#CONNECTIVITY": "multimedia devices connectivity is",
    "multimedia_devices connectivity": "multimedia devices connectivity is",
    "MULTIMEDIA_DEVICES#DESIGN_FEATURES": "multimedia devices design features are",
    "multimedia_devices design_features": "multimedia devices design features are",
    "MULTIMEDIA_DEVICES#GENERAL": "multimedia devices in general are",
    "multimedia_devices general": "multimedia devices in general are",
    "MULTIMEDIA_DEVICES#OPERATION_PERFORMANCE": "multimedia devices operation performance is",
    "multimedia_devices operation_performance": "multimedia devices operation performance is",
    "MULTIMEDIA_DEVICES#PRICE": "multimedia devices price is",
    "multimedia_devices price": "multimedia devices price is",
    "MULTIMEDIA_DEVICES#QUALITY": "multimedia devices quality is",
    "multimedia_devices quality": "multimedia devices quality is",
    "MULTIMEDIA_DEVICES#USABILITY": "multimedia devices usability is",
    "multimedia_devices usability": "multimedia devices usability is",
    "OPTICAL_DRIVES#DESIGN_FEATURES": "optical drives design features are",
    "optical_drives design_features": "optical drives design features are",
    "OPTICAL_DRIVES#GENERAL": "optical drives in general are",
    "optical_drives general": "optical drives in general are",
    "OPTICAL_DRIVES#OPERATION_PERFORMANCE": "optical drives operation performance is",
    "optical_drives operation_performance": "optical drives operation performance is",
    "OPTICAL_DRIVES#USABILITY": "optical drives usability is",
    "optical_drives usability": "optical drives usability is",
    "OS#DESIGN_FEATURES": "os design features are",
    "os design_features": "os design features are",
    "OS#GENERAL": "os in general is",
    "os general": "os in general is",
    "OS#MISCELLANEOUS": "os miscellaneous is",
    "os miscellaneous": "os miscellaneous is",
    "OS#OPERATION_PERFORMANCE": "os operation performance is",
    "os operation_performance": "os operation performance is",
    "OS#PRICE": "os price is",
    "os price": "os price is",
    "OS#QUALITY": "os quality is",
    "os quality": "os quality is",
    "OS#USABILITY": "os usability is",
    "os usability": "os usability is",
    "Out_Of_Scope#DESIGN_FEATURES": "out of scope design features are",
    "out_of_scope design_features": "out of scope design features are",
    "Out_Of_Scope#GENERAL": "out of scope in general is",
    "out_of_scope general": "out of scope in general is",
    "Out_Of_Scope#OPERATION_PERFORMANCE": "out of scope operation performance is",
    "out_of_scope operation_performance": "out of scope operation performance is",
    "Out_Of_Scope#USABILITY": "out of scope usability is",
    "out_of_scope usability": "out of scope usability is",
    "PORTS#CONNECTIVITY": "ports connectivity is",
    "ports connectivity": "ports connectivity is",
    "PORTS#DESIGN_FEATURES": "ports design features are",
    "ports design_features": "ports design features are",
    "PORTS#GENERAL": "ports in general is",
    "ports general": "ports in general is",
    "PORTS#OPERATION_PERFORMANCE": "ports operation performance is",
    "ports operation_performance": "ports operation performance is",
    "PORTS#PORTABILITY": "ports portability is",
    "ports portability": "ports portability is",
    "PORTS#QUALITY": "ports quality is",
    "ports quality": "ports quality is",
    "PORTS#USABILITY": "ports usability is",
    "ports usability": "ports usability is",
    "POWER_SUPPLY#CONNECTIVITY": "power supply connectivity is",
    "power_supply connectivity": "power supply connectivity is",
    "POWER_SUPPLY#DESIGN_FEATURES": "power supply design features are",
    "power_supply design_features": "power supply design features are",
    "POWER_SUPPLY#GENERAL": "power supply in general is",
    "power_supply general": "power supply in general is",
    "POWER_SUPPLY#OPERATION_PERFORMANCE": "power supply operation performance is",
    "power_supply operation_performance": "power supply operation performance is",
    "POWER_SUPPLY#QUALITY": "power supply quality is",
    "power_supply quality": "power supply quality is",
    "RESTAURANT#GENERAL": "restaurant in general is",
    "restaurant general": "restaurant in general is",
    "RESTAURANT#MISCELLANEOUS": "restaurant miscellaneous is",
    "restaurant miscellaneous": "restaurant miscellaneous is",
    "RESTAURANT#PRICES": "restaurant prices are",
    "restaurant prices": "restaurant prices are",
    "SERVICE#GENERAL": "service in general is",
    "service general": "service in general is",
    "SHIPPING#GENERAL": "shipping in general is",
    "shipping general": "shipping in general is",
    "SHIPPING#OPERATION_PERFORMANCE": "shipping operation performance is",
    "shipping operation_performance": "shipping operation performance is",
    "SHIPPING#PRICE": "shipping price is",
    "shipping price": "shipping price is",
    "SHIPPING#QUALITY": "shipping quality is",
    "shipping quality": "shipping quality is",
    "SOFTWARE#DESIGN_FEATURES": "software design features are",
    "software design_features": "software design features are",
    "SOFTWARE#GENERAL": "software in general is",
    "software general": "software in general is",
    "SOFTWARE#OPERATION_PERFORMANCE": "software operation performance is",
    "software operation_performance": "software operation performance is",
    "SOFTWARE#PORTABILITY": "software portability is",
    "software portability": "software portability is",
    "SOFTWARE#PRICE": "software price is",
    "software price": "software price is",
    "SOFTWARE#QUALITY": "software quality is",
    "software quality": "software quality is",
    "SOFTWARE#USABILITY": "software usability is",
    "software usability": "software usability is",
    "SUPPORT#DESIGN_FEATURES": "support design features are",
    "support design_features": "support design features are",
    "SUPPORT#GENERAL": "support in general is",
    "support general": "support in general is",
    "SUPPORT#OPERATION_PERFORMANCE": "support operation performance is",
    "support operation_performance": "support operation performance is",
    "SUPPORT#PRICE": "support price is",
    "support price": "support price is",
    "SUPPORT#QUALITY": "support quality is",
    "support quality": "support quality is",
    "WARRANTY#GENERAL": "warranty in general is",
    "warranty general": "warranty in general is",
    "WARRANTY#QUALITY": "warranty quality is",
    "warranty quality": "warranty quality is",
    "laptop": "laptop",
    "LAPTOP": "laptop",
}


absa_quad_text2category = {
    "ambience general": "AMBIENCE#GENERAL",
    "battery design_features": "BATTERY#DESIGN_FEATURES",
    "battery general": "BATTERY#GENERAL",
    "battery operation_performance": "BATTERY#OPERATION_PERFORMANCE",
    "battery quality": "BATTERY#QUALITY",
    "company design_features": "COMPANY#DESIGN_FEATURES",
    "company general": "COMPANY#GENERAL",
    "company operation_performance": "COMPANY#OPERATION_PERFORMANCE",
    "company price": "COMPANY#PRICE",
    "company quality": "COMPANY#QUALITY",
    "cpu design_features": "CPU#DESIGN_FEATURES",
    "cpu general": "CPU#GENERAL",
    "cpu operation_performance": "CPU#OPERATION_PERFORMANCE",
    "cpu price": "CPU#PRICE",
    "cpu quality": "CPU#QUALITY",
    "display design_features": "DISPLAY#DESIGN_FEATURES",
    "display general": "DISPLAY#GENERAL",
    "display operation_performance": "DISPLAY#OPERATION_PERFORMANCE",
    "display price": "DISPLAY#PRICE",
    "display quality": "DISPLAY#QUALITY",
    "display usability": "DISPLAY#USABILITY",
    "drinks prices": "DRINKS#PRICES",
    "drinks quality": "DRINKS#QUALITY",
    "drinks style_options": "DRINKS#STYLE_OPTIONS",
    "fans&cooling design_features": "FANS&COOLING#DESIGN_FEATURES",
    "fans&cooling general": "FANS&COOLING#GENERAL",
    "fans&cooling operation_performance": "FANS&COOLING#OPERATION_PERFORMANCE",
    "fans&cooling quality": "FANS&COOLING#QUALITY",
    "food general": "FOOD#GENERAL",
    "food prices": "FOOD#PRICES",
    "food quality": "FOOD#QUALITY",
    "food style_options": "FOOD#STYLE_OPTIONS",
    "graphics design_features": "GRAPHICS#DESIGN_FEATURES",
    "graphics general": "GRAPHICS#GENERAL",
    "graphics operation_performance": "GRAPHICS#OPERATION_PERFORMANCE",
    "graphics usability": "GRAPHICS#USABILITY",
    "hardware design_features": "HARDWARE#DESIGN_FEATURES",
    "hardware general": "HARDWARE#GENERAL",
    "hardware operation_performance": "HARDWARE#OPERATION_PERFORMANCE",
    "hardware price": "HARDWARE#PRICE",
    "hardware quality": "HARDWARE#QUALITY",
    "hardware usability": "HARDWARE#USABILITY",
    "hard_disc design_features": "HARD_DISC#DESIGN_FEATURES",
    "hard_disc general": "HARD_DISC#GENERAL",
    "hard_disc miscellaneous": "HARD_DISC#MISCELLANEOUS",
    "hard_disc operation_performance": "HARD_DISC#OPERATION_PERFORMANCE",
    "hard_disc price": "HARD_DISC#PRICE",
    "hard_disc quality": "HARD_DISC#QUALITY",
    "hard_disc usability": "HARD_DISC#USABILITY",
    "keyboard design_features": "KEYBOARD#DESIGN_FEATURES",
    "keyboard general": "KEYBOARD#GENERAL",
    "keyboard miscellaneous": "KEYBOARD#MISCELLANEOUS",
    "keyboard operation_performance": "KEYBOARD#OPERATION_PERFORMANCE",
    "keyboard portability": "KEYBOARD#PORTABILITY",
    "keyboard price": "KEYBOARD#PRICE",
    "keyboard quality": "KEYBOARD#QUALITY",
    "keyboard usability": "KEYBOARD#USABILITY",
    "laptop connectivity": "LAPTOP#CONNECTIVITY",
    "laptop design_features": "LAPTOP#DESIGN_FEATURES",
    "laptop general": "LAPTOP#GENERAL",
    "laptop miscellaneous": "LAPTOP#MISCELLANEOUS",
    "laptop operation_performance": "LAPTOP#OPERATION_PERFORMANCE",
    "laptop portability": "LAPTOP#PORTABILITY",
    "laptop price": "LAPTOP#PRICE",
    "laptop quality": "LAPTOP#QUALITY",
    "laptop usability": "LAPTOP#USABILITY",
    "location general": "LOCATION#GENERAL",
    "memory design_features": "MEMORY#DESIGN_FEATURES",
    "memory general": "MEMORY#GENERAL",
    "memory operation_performance": "MEMORY#OPERATION_PERFORMANCE",
    "memory quality": "MEMORY#QUALITY",
    "memory usability": "MEMORY#USABILITY",
    "motherboard general": "MOTHERBOARD#GENERAL",
    "motherboard operation_performance": "MOTHERBOARD#OPERATION_PERFORMANCE",
    "motherboard quality": "MOTHERBOARD#QUALITY",
    "mouse design_features": "MOUSE#DESIGN_FEATURES",
    "mouse general": "MOUSE#GENERAL",
    "mouse usability": "MOUSE#USABILITY",
    "multimedia_devices connectivity": "MULTIMEDIA_DEVICES#CONNECTIVITY",
    "multimedia_devices design_features": "MULTIMEDIA_DEVICES#DESIGN_FEATURES",
    "multimedia_devices general": "MULTIMEDIA_DEVICES#GENERAL",
    "multimedia_devices operation_performance": "MULTIMEDIA_DEVICES#OPERATION_PERFORMANCE",
    "multimedia_devices price": "MULTIMEDIA_DEVICES#PRICE",
    "multimedia_devices quality": "MULTIMEDIA_DEVICES#QUALITY",
    "multimedia_devices usability": "MULTIMEDIA_DEVICES#USABILITY",
    "optical_drives design_features": "OPTICAL_DRIVES#DESIGN_FEATURES",
    "optical_drives general": "OPTICAL_DRIVES#GENERAL",
    "optical_drives operation_performance": "OPTICAL_DRIVES#OPERATION_PERFORMANCE",
    "optical_drives usability": "OPTICAL_DRIVES#USABILITY",
    "os design_features": "OS#DESIGN_FEATURES",
    "os general": "OS#GENERAL",
    "os miscellaneous": "OS#MISCELLANEOUS",
    "os operation_performance": "OS#OPERATION_PERFORMANCE",
    "os price": "OS#PRICE",
    "os quality": "OS#QUALITY",
    "os usability": "OS#USABILITY",
    "out_of_scope design_features": "Out_Of_Scope#DESIGN_FEATURES",
    "out_of_scope general": "Out_Of_Scope#GENERAL",
    "out_of_scope operation_performance": "Out_Of_Scope#OPERATION_PERFORMANCE",
    "out_of_scope usability": "Out_Of_Scope#USABILITY",
    "ports connectivity": "PORTS#CONNECTIVITY",
    "ports design_features": "PORTS#DESIGN_FEATURES",
    "ports general": "PORTS#GENERAL",
    "ports operation_performance": "PORTS#OPERATION_PERFORMANCE",
    "ports portability": "PORTS#PORTABILITY",
    "ports quality": "PORTS#QUALITY",
    "ports usability": "PORTS#USABILITY",
    "power_supply connectivity": "POWER_SUPPLY#CONNECTIVITY",
    "power_supply design_features": "POWER_SUPPLY#DESIGN_FEATURES",
    "power_supply general": "POWER_SUPPLY#GENERAL",
    "power_supply operation_performance": "POWER_SUPPLY#OPERATION_PERFORMANCE",
    "power_supply quality": "POWER_SUPPLY#QUALITY",
    "restaurant general": "RESTAURANT#GENERAL",
    "restaurant miscellaneous": "RESTAURANT#MISCELLANEOUS",
    "restaurant prices": "RESTAURANT#PRICES",
    "service general": "SERVICE#GENERAL",
    "shipping general": "SHIPPING#GENERAL",
    "shipping operation_performance": "SHIPPING#OPERATION_PERFORMANCE",
    "shipping price": "SHIPPING#PRICE",
    "shipping quality": "SHIPPING#QUALITY",
    "software design_features": "SOFTWARE#DESIGN_FEATURES",
    "software general": "SOFTWARE#GENERAL",
    "software operation_performance": "SOFTWARE#OPERATION_PERFORMANCE",
    "software portability": "SOFTWARE#PORTABILITY",
    "software price": "SOFTWARE#PRICE",
    "software quality": "SOFTWARE#QUALITY",
    "software usability": "SOFTWARE#USABILITY",
    "support design_features": "SUPPORT#DESIGN_FEATURES",
    "support general": "SUPPORT#GENERAL",
    "support operation_performance": "SUPPORT#OPERATION_PERFORMANCE",
    "support price": "SUPPORT#PRICE",
    "support quality": "SUPPORT#QUALITY",
    "warranty general": "WARRANTY#GENERAL",
    "warranty quality": "WARRANTY#QUALITY",
    "laptop": "LAPTOP",
}


# A map to facilitate changing the templates dynamically
# This allows to do the pre-finetuning and finetuning with a single script
# provided that the parameters are changed accordingly
template_map = {
    "main_templates": main_templates,
    "noisy_templates": noisy_templates,
    "no_templates": no_templates,
}
